### PR TITLE
Slow

### PR DESCRIPTION
**Pull request by brandenbyers**
For added suspense...

Two options, either 5 seconds before each name is displayed, or 2 seconds between. Adds more suspense. Can easily be changed by changing which css file is being sourced.

### CODE REVIEW

**Comment by jetpacktuxedo** [comment]
can't you do loops in CSS instead of manually listing all of them?

**Comment by brandenbyers** [comment]
This is written in Sass, which has loops. I’m converting it to CSS which has no such concepts if loops. I’m definitely editing those by hand! 😜

**Comment by jameshly** [comment]
Bring me my red stamp...

**Comment by jetpacktuxedo** [comment]
rip

**Comment by jetpacktuxedo** [comment]
lmao

**Comment by jetpacktuxedo** [comment]
lgtm 👍

**Pull request closed without merging**
